// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMxUpjjj-Yi6A2gQKGYPxFK0WbioTERL8',
    appId: '1:1001656102686:web:c02e0a1cd1b7ab95c5e30f',
    messagingSenderId: '1001656102686',
    projectId: 'ecommerce-437c9',
    authDomain: 'ecommerce-437c9.firebaseapp.com',
    storageBucket: 'ecommerce-437c9.firebasestorage.app',
    measurementId: 'G-07SD95F405',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRXfp9r4j0csJJz6vVq7wbauA2lbk52RQ',
    appId: '1:1001656102686:android:bf642a498c5c2967c5e30f',
    messagingSenderId: '1001656102686',
    projectId: 'ecommerce-437c9',
    storageBucket: 'ecommerce-437c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC8F_GNieHIFXP9N0n1T1FX-U0oEz6GK0',
    appId: '1:1001656102686:ios:4e83445fe45435c1c5e30f',
    messagingSenderId: '1001656102686',
    projectId: 'ecommerce-437c9',
    storageBucket: 'ecommerce-437c9.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC8F_GNieHIFXP9N0n1T1FX-U0oEz6GK0',
    appId: '1:1001656102686:ios:4e83445fe45435c1c5e30f',
    messagingSenderId: '1001656102686',
    projectId: 'ecommerce-437c9',
    storageBucket: 'ecommerce-437c9.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMxUpjjj-Yi6A2gQKGYPxFK0WbioTERL8',
    appId: '1:1001656102686:web:26a42ff91a33ae0cc5e30f',
    messagingSenderId: '1001656102686',
    projectId: 'ecommerce-437c9',
    authDomain: 'ecommerce-437c9.firebaseapp.com',
    storageBucket: 'ecommerce-437c9.firebasestorage.app',
    measurementId: 'G-6NBE6KYHYT',
  );

}